// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: jarvis.proto

package server

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CommandStream_ServerStream_FullMethodName = "/jarvis.v1.CommandStream/ServerStream"
)

// CommandStreamClient is the client API for CommandStream service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CommandStreamClient interface {
	ServerStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[Request, Response], error)
}

type commandStreamClient struct {
	cc grpc.ClientConnInterface
}

func NewCommandStreamClient(cc grpc.ClientConnInterface) CommandStreamClient {
	return &commandStreamClient{cc}
}

func (c *commandStreamClient) ServerStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[Request, Response], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &CommandStream_ServiceDesc.Streams[0], CommandStream_ServerStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Request, Response]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CommandStream_ServerStreamClient = grpc.BidiStreamingClient[Request, Response]

// CommandStreamServer is the server API for CommandStream service.
// All implementations must embed UnimplementedCommandStreamServer
// for forward compatibility.
type CommandStreamServer interface {
	ServerStream(grpc.BidiStreamingServer[Request, Response]) error
	mustEmbedUnimplementedCommandStreamServer()
}

// UnimplementedCommandStreamServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCommandStreamServer struct{}

func (UnimplementedCommandStreamServer) ServerStream(grpc.BidiStreamingServer[Request, Response]) error {
	return status.Errorf(codes.Unimplemented, "method ServerStream not implemented")
}
func (UnimplementedCommandStreamServer) mustEmbedUnimplementedCommandStreamServer() {}
func (UnimplementedCommandStreamServer) testEmbeddedByValue()                       {}

// UnsafeCommandStreamServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CommandStreamServer will
// result in compilation errors.
type UnsafeCommandStreamServer interface {
	mustEmbedUnimplementedCommandStreamServer()
}

func RegisterCommandStreamServer(s grpc.ServiceRegistrar, srv CommandStreamServer) {
	// If the following call pancis, it indicates UnimplementedCommandStreamServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CommandStream_ServiceDesc, srv)
}

func _CommandStream_ServerStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(CommandStreamServer).ServerStream(&grpc.GenericServerStream[Request, Response]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CommandStream_ServerStreamServer = grpc.BidiStreamingServer[Request, Response]

// CommandStream_ServiceDesc is the grpc.ServiceDesc for CommandStream service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CommandStream_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "jarvis.v1.CommandStream",
	HandlerType: (*CommandStreamServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ServerStream",
			Handler:       _CommandStream_ServerStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "jarvis.proto",
}
