apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: jarvis-agent
  namespace: jarvis
  labels:
    app: jarvis-agent
spec:
  selector:
    matchLabels:
      app: jarvis-agent
  template:
    metadata:
      labels:
        app: jarvis-agent
    spec:
      tolerations:
        - operator: Exists
      hostPID: true
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
        - name: agent
          image: docker.io/jm98/jarvis-agent:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 50051
              name: grpc
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          volumeMounts:
            - name: var-run
              mountPath: /var/run
            - name: host-root
              mountPath: /host
              readOnly: true
          securityContext:
            privileged: true
      volumes:
        - name: var-run
          hostPath:
            path: /var/run
            type: DirectoryOrCreate
        - name: host-root
          hostPath:
            path: /
            type: Directory
      serviceAccountName: jarvis-agent
