// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.29.3
// source: jarvis.proto

package agent

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeName      string                 `protobuf:"bytes,1,opt,name=nodeName,proto3" json:"nodeName,omitempty"`
	Result        *CommandResult         `protobuf:"bytes,2,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_jarvis_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_jarvis_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_jarvis_proto_rawDescGZIP(), []int{0}
}

func (x *Response) GetNodeName() string {
	if x != nil {
		return x.NodeName
	}
	return ""
}

func (x *Response) GetResult() *CommandResult {
	if x != nil {
		return x.Result
	}
	return nil
}

type Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Command       *CommandRequest        `protobuf:"bytes,1,opt,name=command,proto3" json:"command,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Request) Reset() {
	*x = Request{}
	mi := &file_jarvis_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_jarvis_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_jarvis_proto_rawDescGZIP(), []int{1}
}

func (x *Request) GetCommand() *CommandRequest {
	if x != nil {
		return x.Command
	}
	return nil
}

type CommandRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Cmd           string                 `protobuf:"bytes,2,opt,name=cmd,proto3" json:"cmd,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandRequest) Reset() {
	*x = CommandRequest{}
	mi := &file_jarvis_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandRequest) ProtoMessage() {}

func (x *CommandRequest) ProtoReflect() protoreflect.Message {
	mi := &file_jarvis_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandRequest.ProtoReflect.Descriptor instead.
func (*CommandRequest) Descriptor() ([]byte, []int) {
	return file_jarvis_proto_rawDescGZIP(), []int{2}
}

func (x *CommandRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CommandRequest) GetCmd() string {
	if x != nil {
		return x.Cmd
	}
	return ""
}

type CommandResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Output        string                 `protobuf:"bytes,2,opt,name=output,proto3" json:"output,omitempty"`
	ExitCode      int32                  `protobuf:"varint,3,opt,name=exitCode,proto3" json:"exitCode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandResult) Reset() {
	*x = CommandResult{}
	mi := &file_jarvis_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandResult) ProtoMessage() {}

func (x *CommandResult) ProtoReflect() protoreflect.Message {
	mi := &file_jarvis_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandResult.ProtoReflect.Descriptor instead.
func (*CommandResult) Descriptor() ([]byte, []int) {
	return file_jarvis_proto_rawDescGZIP(), []int{3}
}

func (x *CommandResult) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CommandResult) GetOutput() string {
	if x != nil {
		return x.Output
	}
	return ""
}

func (x *CommandResult) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

var File_jarvis_proto protoreflect.FileDescriptor

const file_jarvis_proto_rawDesc = "" +
	"\n" +
	"\fjarvis.proto\x12\tjarvis.v1\"X\n" +
	"\bResponse\x12\x1a\n" +
	"\bnodeName\x18\x01 \x01(\tR\bnodeName\x120\n" +
	"\x06result\x18\x02 \x01(\v2\x18.jarvis.v1.CommandResultR\x06result\">\n" +
	"\aRequest\x123\n" +
	"\acommand\x18\x01 \x01(\v2\x19.jarvis.v1.CommandRequestR\acommand\"2\n" +
	"\x0eCommandRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x10\n" +
	"\x03cmd\x18\x02 \x01(\tR\x03cmd\"S\n" +
	"\rCommandResult\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06output\x18\x02 \x01(\tR\x06output\x12\x1a\n" +
	"\bexitCode\x18\x03 \x01(\x05R\bexitCode2L\n" +
	"\rCommandStream\x12;\n" +
	"\fServerStream\x12\x12.jarvis.v1.Request\x1a\x13.jarvis.v1.Response(\x010\x01B\"Z github.com/motilayo/jarvis/agentb\x06proto3"

var (
	file_jarvis_proto_rawDescOnce sync.Once
	file_jarvis_proto_rawDescData []byte
)

func file_jarvis_proto_rawDescGZIP() []byte {
	file_jarvis_proto_rawDescOnce.Do(func() {
		file_jarvis_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_jarvis_proto_rawDesc), len(file_jarvis_proto_rawDesc)))
	})
	return file_jarvis_proto_rawDescData
}

var file_jarvis_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_jarvis_proto_goTypes = []any{
	(*Response)(nil),       // 0: jarvis.v1.Response
	(*Request)(nil),        // 1: jarvis.v1.Request
	(*CommandRequest)(nil), // 2: jarvis.v1.CommandRequest
	(*CommandResult)(nil),  // 3: jarvis.v1.CommandResult
}
var file_jarvis_proto_depIdxs = []int32{
	3, // 0: jarvis.v1.Response.result:type_name -> jarvis.v1.CommandResult
	2, // 1: jarvis.v1.Request.command:type_name -> jarvis.v1.CommandRequest
	1, // 2: jarvis.v1.CommandStream.ServerStream:input_type -> jarvis.v1.Request
	0, // 3: jarvis.v1.CommandStream.ServerStream:output_type -> jarvis.v1.Response
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_jarvis_proto_init() }
func file_jarvis_proto_init() {
	if File_jarvis_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_jarvis_proto_rawDesc), len(file_jarvis_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_jarvis_proto_goTypes,
		DependencyIndexes: file_jarvis_proto_depIdxs,
		MessageInfos:      file_jarvis_proto_msgTypes,
	}.Build()
	File_jarvis_proto = out.File
	file_jarvis_proto_goTypes = nil
	file_jarvis_proto_depIdxs = nil
}
